version: '3.8'

services:
  app:
    build: .
    container_name: tgBot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=2778
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2778
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
